-- Antaaya Villas CRM — Full Schema (current: schema v2 + migration_v3 … migration_v37)
--
-- FRESH INSTALL ONLY. Import via phpMyAdmin into an EMPTY database. It creates every table the CRM
-- uses today and the villa inventory (same list as migration_v12.sql), so none of the migration_v*.sql
-- files need to be run after it.
--
-- Your live database already has all of this — do NOT import this file there (use the migration
-- files for upgrades, as before).
--
-- Then create the first login (an IT or Admin user) — the password must be a PHP password_hash(),
-- e.g. from a one-off seed.php, then delete that script.

SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE `assignment_log` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) DEFAULT NULL,
  `source_lead_id` int(11) DEFAULT NULL,
  `label` varchar(191) DEFAULT NULL,
  `from_user_id` int(11) DEFAULT NULL,
  `to_user_id` int(11) DEFAULT NULL,
  `type` varchar(30) NOT NULL DEFAULT 'assigned',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  KEY `to_user_id` (`to_user_id`),
  KEY `source_lead_id` (`source_lead_id`),
  CONSTRAINT `assignment_log_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `assignment_log_ibfk_2` FOREIGN KEY (`to_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `assignment_log_ibfk_3` FOREIGN KEY (`source_lead_id`) REFERENCES `source_leads` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `client_documents` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `doc_type` varchar(40) NOT NULL,
  `doc_label` varchar(191) DEFAULT NULL,
  `stage` varchar(50) DEFAULT NULL,
  `original_name` varchar(255) NOT NULL,
  `stored_name` varchar(255) NOT NULL,
  `mime` varchar(100) DEFAULT NULL,
  `size` int(11) DEFAULT NULL,
  `uploaded_by` int(11) DEFAULT NULL,
  `uploaded_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_client_doc` (`client_id`,`doc_type`),
  CONSTRAINT `client_documents_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `client_payments` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `demand_id` int(11) DEFAULT NULL,
  `pay_date` date NOT NULL,
  `amount` decimal(14,2) NOT NULL,
  `mode` varchar(40) DEFAULT NULL,
  `ref_no` varchar(100) DEFAULT NULL,
  `note` text DEFAULT NULL,
  `source` varchar(20) NOT NULL DEFAULT 'accounts',
  `doc_id` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_pay_client` (`client_id`),
  CONSTRAINT `client_payments_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `clients` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `lead_code` varchar(10) DEFAULT NULL,
  `name` varchar(150) NOT NULL,
  `mobile` varchar(20) NOT NULL,
  `alt_mobile` varchar(20) DEFAULT NULL,
  `whatsapp` varchar(20) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `source` varchar(50) DEFAULT NULL,
  `subsource` varchar(100) DEFAULT NULL,
  `salesperson_id` int(11) NOT NULL,
  `created_date` date DEFAULT NULL,
  `purpose` varchar(50) DEFAULT NULL,
  `config` varchar(50) DEFAULT NULL,
  `budget` varchar(50) DEFAULT NULL,
  `budget_confirmed` varchar(20) DEFAULT NULL,
  `decision_maker` varchar(10) DEFAULT NULL,
  `finance` varchar(50) DEFAULT NULL,
  `req_whatsapp_message` text DEFAULT NULL,
  `req_whatsapp_sent` varchar(10) DEFAULT NULL,
  `interest` enum('HOT','WARM','COLD') DEFAULT 'WARM',
  `stage` varchar(50) DEFAULT 'New Lead',
  `cancelled_reason` varchar(255) DEFAULT NULL,
  `category` enum('Broker','Broker Reference','Owner') DEFAULT NULL,
  `broker_name` varchar(150) DEFAULT NULL,
  `broker_contact` varchar(20) DEFAULT NULL,
  `broker_email` varchar(150) DEFAULT NULL,
  `entry_channel` enum('Form','CRM') NOT NULL DEFAULT 'CRM',
  `entry_type` enum('Enquiry','Broker Visit','Site Visit','Manual') NOT NULL DEFAULT 'Manual',
  `created_by` int(11) DEFAULT NULL,
  `firstcall_date` date DEFAULT NULL,
  `call_attempt_result` varchar(30) DEFAULT NULL,
  `attempt_time` time DEFAULT NULL,
  `lastcontact_date` date DEFAULT NULL,
  `nextfollow_date` date DEFAULT NULL,
  `followup_mode` varchar(30) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `activity_log` text DEFAULT NULL,
  `nextaction` text DEFAULT NULL,
  `brochure_date` date DEFAULT NULL,
  `brochure_mode` varchar(30) DEFAULT NULL,
  `brochure_whatsapp_message` text DEFAULT NULL,
  `brochure_whatsapp_sent` varchar(10) DEFAULT NULL,
  `brochure_bypass` varchar(10) DEFAULT NULL,
  `visit_invite_uid` varchar(80) DEFAULT NULL,
  `visit_invite_seq` int(11) NOT NULL DEFAULT 0,
  `visit_invite_sent_at` datetime DEFAULT NULL,
  `visit_invite_for` varchar(80) DEFAULT NULL,
  `visit_status` varchar(30) DEFAULT 'Not Scheduled',
  `visit_date` date DEFAULT NULL,
  `visit_time` time DEFAULT NULL,
  `visit_villa` varchar(50) DEFAULT NULL,
  `visit_pickup` varchar(10) DEFAULT NULL,
  `visit_whatsapp_sent` varchar(10) DEFAULT NULL,
  `visit_visitors` int(11) DEFAULT 1,
  `visit_outcome` varchar(50) DEFAULT NULL,
  `revisit_date` date DEFAULT NULL,
  `revisit_time` time DEFAULT NULL,
  `revisit_whatsapp_sent` varchar(10) DEFAULT NULL,
  `revisit_invite_uid` varchar(80) DEFAULT NULL,
  `revisit_invite_seq` int(11) NOT NULL DEFAULT 0,
  `revisit_invite_sent_at` datetime DEFAULT NULL,
  `revisit_invite_for` varchar(80) DEFAULT NULL,
  `negotiation_visit_date` date DEFAULT NULL,
  `negotiation_visit_time` time DEFAULT NULL,
  `negotiation_whatsapp_sent` varchar(10) DEFAULT NULL,
  `negotiation_invite_uid` varchar(80) DEFAULT NULL,
  `negotiation_invite_seq` int(11) NOT NULL DEFAULT 0,
  `negotiation_invite_sent_at` datetime DEFAULT NULL,
  `negotiation_invite_for` varchar(80) DEFAULT NULL,
  `revisit_outcome` varchar(50) DEFAULT NULL,
  `revisit_villa` varchar(100) DEFAULT NULL,
  `revisit_visitors` int(11) DEFAULT 1,
  `revisit_feedback` text DEFAULT NULL,
  `visit_feedback` text DEFAULT NULL,
  `offered_price` varchar(500) DEFAULT NULL,
  `villa_offers` text DEFAULT NULL,
  `negotiation_notes` text DEFAULT NULL,
  `villa` varchar(500) DEFAULT NULL,
  `villa_shortlist` varchar(255) DEFAULT NULL,
  `villa_selected` varchar(50) DEFAULT NULL,
  `block_date` date DEFAULT NULL,
  `token_amount` decimal(14,2) DEFAULT 0.00,
  `final_villa_price` varchar(50) DEFAULT NULL,
  `block_note` text DEFAULT NULL,
  `salevalue` decimal(14,2) DEFAULT 0.00,
  `confirmation_date` date DEFAULT NULL,
  `bookingamount` decimal(14,2) DEFAULT 0.00,
  `bookingdate` date DEFAULT NULL,
  `agreement` varchar(30) DEFAULT 'Pending',
  `agreement_date` date DEFAULT NULL,
  `agreement_notes` text DEFAULT NULL,
  `registration` varchar(30) DEFAULT 'Pending',
  `registration_date` date DEFAULT NULL,
  `received` decimal(14,2) DEFAULT 0.00,
  `duedate` date DEFAULT NULL,
  `dueamount` decimal(14,2) DEFAULT 0.00,
  `loan` varchar(30) DEFAULT 'N/A',
  `construction` varchar(30) DEFAULT 'Not Started',
  `fitout` varchar(30) DEFAULT 'Pending',
  `expected_possession_date` date DEFAULT NULL,
  `inspection` varchar(30) DEFAULT 'Pending',
  `snagging` varchar(30) DEFAULT 'Pending',
  `posletter` varchar(30) DEFAULT 'Pending',
  `posdate` date DEFAULT NULL,
  `handover` date DEFAULT NULL,
  `keys_handed` varchar(10) DEFAULT 'No',
  `sv_followup_date` date DEFAULT NULL,
  `sv_followup_mode` varchar(30) DEFAULT NULL,
  `sv_followup_note` text DEFAULT NULL,
  `sv_refollow` varchar(10) DEFAULT NULL,
  `sv_refollow_date` date DEFAULT NULL,
  `psv_followup_date` date DEFAULT NULL,
  `psv_followup_mode` varchar(30) DEFAULT NULL,
  `psv_followup_note` text DEFAULT NULL,
  `psv_refollow` varchar(10) DEFAULT NULL,
  `psv_refollow_date` date DEFAULT NULL,
  `rv_followup_date` date DEFAULT NULL,
  `rv_followup_mode` varchar(30) DEFAULT NULL,
  `rv_followup_note` text DEFAULT NULL,
  `rv_refollow` varchar(10) DEFAULT NULL,
  `rv_refollow_date` date DEFAULT NULL,
  `nv_followup_date` date DEFAULT NULL,
  `nv_followup_mode` varchar(30) DEFAULT NULL,
  `nv_followup_note` text DEFAULT NULL,
  `nv_refollow` varchar(10) DEFAULT NULL,
  `nv_refollow_date` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `booking_payment_mode` varchar(30) DEFAULT NULL,
  `booking_txn_ref` varchar(100) DEFAULT NULL,
  `booking_form_status` varchar(20) DEFAULT NULL,
  `applicant_type` varchar(40) DEFAULT NULL,
  `applicant_pan` varchar(10) DEFAULT NULL,
  `applicant_aadhaar_last4` varchar(4) DEFAULT NULL,
  `applicant_dob` date DEFAULT NULL,
  `applicant_occupation` varchar(100) DEFAULT NULL,
  `applicant_address` text DEFAULT NULL,
  `co_applicant_name` varchar(150) DEFAULT NULL,
  `co_applicant_relation` varchar(50) DEFAULT NULL,
  `co_applicant_pan` varchar(10) DEFAULT NULL,
  `co_applicant_aadhaar_last4` varchar(4) DEFAULT NULL,
  `kyc_status` varchar(20) DEFAULT NULL,
  `kyc_verified_date` date DEFAULT NULL,
  `kyc_note` text DEFAULT NULL,
  `allotment_letter` varchar(20) DEFAULT NULL,
  `allotment_date` date DEFAULT NULL,
  `draft_agreement_date` date DEFAULT NULL,
  `stamp_duty_amount` decimal(14,2) DEFAULT NULL,
  `registration_fee` decimal(14,2) DEFAULT NULL,
  `stamp_duty_paid` varchar(10) DEFAULT NULL,
  `registration_doc_no` varchar(100) DEFAULT NULL,
  `sub_registrar_office` varchar(150) DEFAULT NULL,
  `payment_plan` varchar(40) DEFAULT NULL,
  `construction_milestone` varchar(60) DEFAULT NULL,
  `construction_update_date` date DEFAULT NULL,
  `last_payment_date` date DEFAULT NULL,
  `loan_bank` varchar(100) DEFAULT NULL,
  `vb_followup_date` date DEFAULT NULL,
  `vb_followup_mode` varchar(30) DEFAULT NULL,
  `vb_followup_note` text DEFAULT NULL,
  `vb_refollow` varchar(10) DEFAULT NULL,
  `vb_refollow_date` date DEFAULT NULL,
  `sales_handover_at` datetime DEFAULT NULL,
  `sales_handover_by` int(11) DEFAULT NULL,
  `accounts_handover_at` datetime DEFAULT NULL,
  `accounts_handover_by` int(11) DEFAULT NULL,
  `pay_demanded` decimal(14,2) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `lead_code` (`lead_code`),
  KEY `salesperson_id` (`salesperson_id`),
  KEY `created_by` (`created_by`),
  CONSTRAINT `clients_ibfk_1` FOREIGN KEY (`salesperson_id`) REFERENCES `users` (`id`),
  CONSTRAINT `clients_ibfk_2` FOREIGN KEY (`created_by`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `followups` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `salesperson_id` int(11) NOT NULL,
  `followup_date` date NOT NULL,
  `mode` varchar(30) DEFAULT NULL,
  `followup_type` varchar(50) DEFAULT NULL,
  `interest` enum('HOT','WARM','COLD') DEFAULT 'WARM',
  `next_date` date DEFAULT NULL,
  `status` enum('Pending','Completed','Rescheduled') DEFAULT 'Pending',
  `discussion` text DEFAULT NULL,
  `response` text DEFAULT NULL,
  `next_action` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  KEY `salesperson_id` (`salesperson_id`),
  CONSTRAINT `followups_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `followups_ibfk_2` FOREIGN KEY (`salesperson_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `lead_transfer_requests` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `from_user_id` int(11) NOT NULL,
  `to_user_id` int(11) NOT NULL,
  `status` enum('Pending','Confirmed','Rejected') NOT NULL DEFAULT 'Pending',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `resolved_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  KEY `from_user_id` (`from_user_id`),
  KEY `to_user_id` (`to_user_id`),
  CONSTRAINT `lead_transfer_requests_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE,
  CONSTRAINT `lead_transfer_requests_ibfk_2` FOREIGN KEY (`from_user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `lead_transfer_requests_ibfk_3` FOREIGN KEY (`to_user_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `notification_clears` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `assignment_log_id` int(11) NOT NULL,
  `cleared_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniq_user_log` (`user_id`,`assignment_log_id`),
  KEY `assignment_log_id` (`assignment_log_id`),
  CONSTRAINT `notification_clears_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`),
  CONSTRAINT `notification_clears_ibfk_2` FOREIGN KEY (`assignment_log_id`) REFERENCES `assignment_log` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `payment_demands` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `schedule_id` int(11) NOT NULL,
  `demand_no` int(11) NOT NULL,
  `demand_date` date NOT NULL,
  `due_date` date NOT NULL,
  `instalment` decimal(14,2) NOT NULL,
  `carried_forward` decimal(14,2) NOT NULL DEFAULT 0.00,
  `advance_adjusted` decimal(14,2) NOT NULL DEFAULT 0.00,
  `total_due` decimal(14,2) NOT NULL,
  `status` varchar(20) NOT NULL DEFAULT 'Open',
  `note` text DEFAULT NULL,
  `email_sent_at` datetime DEFAULT NULL,
  `email_to` varchar(191) DEFAULT NULL,
  `email_count` int(11) NOT NULL DEFAULT 0,
  `whatsapp_sent_at` datetime DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_dem_client` (`client_id`),
  CONSTRAINT `payment_demands_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `payment_plans` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `base_price` decimal(14,2) NOT NULL,
  `due_days` int(11) NOT NULL DEFAULT 15,
  `plan_name` varchar(60) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_at` datetime DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_plan_client` (`client_id`),
  CONSTRAINT `payment_plans_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `payment_schedule` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `seq` tinyint(4) NOT NULL,
  `code` varchar(30) NOT NULL,
  `label` varchar(191) NOT NULL,
  `pct` decimal(6,3) NOT NULL,
  `amount` decimal(14,2) NOT NULL,
  `milestone_date` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_sched` (`client_id`,`seq`),
  CONSTRAINT `payment_schedule_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `source_leads` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `site` varchar(30) NOT NULL,
  `form_type` varchar(40) NOT NULL,
  `name` varchar(150) DEFAULT NULL,
  `mobile` varchar(20) DEFAULT NULL,
  `alt_mobile` varchar(20) DEFAULT NULL,
  `email` varchar(150) DEFAULT NULL,
  `city` varchar(100) DEFAULT NULL,
  `source` varchar(50) DEFAULT NULL,
  `subsource` varchar(100) DEFAULT NULL,
  `budget` varchar(50) DEFAULT NULL,
  `config` varchar(50) DEFAULT NULL,
  `purpose` varchar(50) DEFAULT NULL,
  `category` enum('Broker','Owner') DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `raw_data` longtext DEFAULT NULL,
  `status` enum('New','Assigned','Rejected') NOT NULL DEFAULT 'New',
  `reviewed_by` int(11) DEFAULT NULL,
  `reviewed_at` timestamp NULL DEFAULT NULL,
  `assigned_lead_id` int(11) DEFAULT NULL,
  `assigned_salesperson_id` int(11) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `reviewed_by` (`reviewed_by`),
  KEY `assigned_lead_id` (`assigned_lead_id`),
  KEY `assigned_salesperson_id` (`assigned_salesperson_id`),
  CONSTRAINT `source_leads_ibfk_1` FOREIGN KEY (`reviewed_by`) REFERENCES `users` (`id`),
  CONSTRAINT `source_leads_ibfk_2` FOREIGN KEY (`assigned_lead_id`) REFERENCES `clients` (`id`),
  CONSTRAINT `source_leads_ibfk_3` FOREIGN KEY (`assigned_salesperson_id`) REFERENCES `users` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `users` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `email` varchar(150) NOT NULL,
  `password_hash` varchar(255) NOT NULL,
  `role` enum('admin','sales','legal','accounts','it') NOT NULL DEFAULT 'sales',
  `desk` enum('entry','broker','owner','legal','accounts') DEFAULT NULL,
  `photo` varchar(255) DEFAULT NULL,
  `smtp_app_password` varchar(400) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `villas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) NOT NULL,
  `serial` varchar(50) NOT NULL,
  `villa_type` enum('rhs','lhs','combo') NOT NULL,
  `status` enum('available','blocked','negotiation','booked','sold') NOT NULL DEFAULT 'available',
  `linked_client_id` int(11) DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name` (`name`),
  UNIQUE KEY `serial` (`serial`),
  KEY `linked_client_id` (`linked_client_id`),
  CONSTRAINT `villas_ibfk_1` FOREIGN KEY (`linked_client_id`) REFERENCES `clients` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `visits` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `client_id` int(11) NOT NULL,
  `kind` varchar(20) NOT NULL DEFAULT 'site',
  `visit_date` date NOT NULL,
  `visit_time` time DEFAULT NULL,
  `visitors` int(11) DEFAULT 1,
  `villa` varchar(500) DEFAULT NULL,
  `status` varchar(30) DEFAULT 'Scheduled',
  `outcome` varchar(50) DEFAULT NULL,
  `feedback` text DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `client_id` (`client_id`),
  CONSTRAINT `visits_ibfk_1` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Villa Inventory (from migration_v12.sql)
INSERT INTO villas (name, serial, villa_type, status) VALUES
('ALARA 1',  'A1-01',  'rhs',   'available'),
('ALARA 2',  'A1-02',  'lhs',   'available'),
('ALARA 3',  'A2-01',  'rhs',   'available'),
('ALARA 4',  'A2-02',  'lhs',   'available'),
('ALARA 5',  'A3-01',  'rhs',   'sold'),
('ALARA 6',  'A3-02',  'lhs',   'sold'),
('EMIRA 1',  'A4-1,2', 'combo', 'available'),
('ALARA 9',  'A5-01',  'lhs',   'sold'),
('ALARA 8',  'A5-02',  'rhs',   'sold'),
('EMIRA 2',  'A6-1,2', 'combo', 'available'),
('ALARA 10', 'A7-01',  'rhs',   'available'),
('ALARA 11', 'A7-02',  'lhs',   'sold'),
('ALARA 12', 'A8-01',  'rhs',   'sold'),
('ALARA 13', 'A8-02',  'lhs',   'sold'),
('ALARA 14', 'A9-01',  'rhs',   'available'),
('ALARA 15', 'A9-02',  'lhs',   'available'),
('EMIRA 3',  'A10-1,2','combo', 'sold'),
('ALARA 16', 'A11-01', 'lhs',   'sold'),
('ALARA 17', 'A11-02', 'rhs',   'sold'),
('ALARA 7',  'B1-01',  'rhs',   'available');

SET FOREIGN_KEY_CHECKS = 1;
